### ISSUE TITLE
[2.7.4] Plot auto major error

### ISSUE THREAD

**Issue by brunyman** [IntellectualCrafters/PlotSquared#160]
I use the spigot 1.8, the main world named: world is used as spawn and the plots are in world: world_creative. If I type /plot auto from spawn world i get this error, it claims a plot but does not teleport me there, so i have to also do /plot home to get to the plot. If we run /plot auto from plots world we do not get the error. We use offline uuids.
Full server log: http://pastebin.com/4b4tjEnQ

[10:39:56] [Server thread/INFO]: brunyman[/79.112.234.20:52170] logged in with entity id 200 at ([world] -501.5, 20.0, 36.07790998226173)
[10:40:01] [Server thread/INFO]: brunyman issued server command: /plot auto
[10:40:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v2.7.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_51]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]
Caused by: java.lang.NullPointerException
	at com.intellectualcrafters.plot.util.PlotHelper.createPlot(PlotHelper.java:521) ~[?:?]
	at com.intellectualcrafters.plot.commands.Claim.claimPlot(Claim.java:59) ~[?:?]
	at com.intellectualcrafters.plot.commands.Claim.claimPlot(Claim.java:49) ~[?:?]
	at com.intellectualcrafters.plot.commands.Auto.execute(Auto.java:204) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:192) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-0643caa]
	... 14 more

**Comment by boy0001** [comment]
Should be resolved in latest dev build
