### ISSUE TITLE
plot list mine bug

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#183]
[01:04:40 INFO]: TomBanks issued server command: /plot list mine
[01:04:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v2.8.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[creative.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[creative.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[creative.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [creative.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [creative.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [creative.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [creative.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [creative.jar:git-Spigot-c3c767f-33d5de3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [creative.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [creative.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [creative.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [creative.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:773) ~[?:1.8.0_40]
        at java.util.TimSort.mergeAt(TimSort.java:510) ~[?:1.8.0_40]
        at java.util.TimSort.mergeCollapse(TimSort.java:437) ~[?:1.8.0_40]
        at java.util.TimSort.sort(TimSort.java:241) ~[?:1.8.0_40]
        at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_40]
        at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_40]
        at java.util.Collections.sort(Collections.java:175) ~[?:1.8.0_40]
        at com.intellectualcrafters.plot.PlotSquared.sortPlots(PlotSquared.java:148) ~[?:?]
        at com.intellectualcrafters.plot.commands.list.displayPlots(list.java:197) ~[?:?]
        at com.intellectualcrafters.plot.commands.list.execute(list.java:192) ~[?:?]
        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:170) ~[?:?]
        at com.intellectualcrafters.plot.commands.BukkitCommand.onCommand(BukkitCommand.java:26) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[creative.jar:git-Spigot-c3c767f-33d5de3]
        ... 14 more

**Comment by boy0001** [comment]
Fixed as of: d5fe805d8f12ec9f5bc0a7e2a7c746a9034ff2b8
