### ISSUE TITLE
Cant Save or export schematics

### ISSUE THREAD

**Issue by flamboo** [IntellectualCrafters/PlotSquared#213]
hi, I love the plugin but I can not use the /p sch <save>,<export>,<exportall> commands

Here is what it says in console 
```java
[15:47:46 INFO]: flamboo issued server command: /p sch save 
[15:47:49 WARN]: java.io.FileNotFoundException: /plugins/plotSquared/schematics/0;-1,plot,flamboo.schematic (No such file or directory) 
[15:47:49 WARN]: at java.io.FileOutputStream.open(Native Method) 
[15:47:49 WARN]: at java.io.FileOutputStream.<init>(FileOutputStream.java:221) 
[15:47:49 WARN]: at java.io.FileOutputStream.<init>(FileOutputStream.java:110) 
[15:47:49 WARN]: at com.intellectualcrafters.plot.util.SchematicHandler.save(SchematicHandler.java:218) 
[15:47:49 WARN]: at com.intellectualcrafters.plot.commands.SchematicCmd$3$1.run(SchematicCmd.java:315) 
[15:47:49 WARN]: at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) 
[15:47:49 WARN]: at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 
[15:47:49 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
[15:47:49 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 
```

and here is my config.

```yml
version: 2.8.11
schematics:
  save_path: /plugins/plotSquared/schematics
uuid:
  read-from-disk: false
claim:
  max-auto-area: 1
max_plots: 127
console:
  color: true
teleport:
  on_login: false
  delay: 0
debug: true
clusters:
  enabled: true
auto_update: false
plotme-convert:
  enabled: true
kill_road_mobs: true
confirmation:
  unlink: true
  delete: true
  clear: true
metrics: true
cache:
  permissions: false
plotme-alias: false
clear:
  auto:
    enabled: false
    days: 365
  check-disk: false
  'on':
    ban: false
mob_pathfinding: true
worldedit:
  require-selection-in-mask: true
titles: true
UUID:
  offline: false
worlds:
  plot:
    plot:
      height: 64
      size: 31
      filling:
      - '1:0'
      floor:
      - '2:0'
      bedrock: true
      biome: FOREST
      create_signs: true
      auto_merge: false
    wall:
      block: '44:7'
      block_claimed: '44:0'
      filling: '1:0'
      height: 64
    road:
      width: 7
      height: 64
      block: '155:0'
    event:
      spawn:
        breeding: false
        egg: false
        custom: true
      pvp: false
      pve: false
    economy:
      use: false
      prices:
        claim: 100.0
        sell: 75.0
        merge: 100.0
```

**Comment by boy0001** [comment]
The directory needs to be absolute rather than relative.

**Comment by boy0001** [comment]
Please re-open or comment if still an issue.

**Comment by flamboo** [comment]
How would I get the absolute directory on shared hosting ?

**Comment by EvilOlaf** [comment]
Good point. Let the schematics export to the PlotSquared/exports or whatever directory. Just a fraction of all minecraft servers would have a dedicated root server or similar where also a httpd is installed too.

**Comment by boy0001** [comment]
Then the issue is all the servers upgrading are going to have issues.

**Comment by boy0001** [comment]
Just realized.

Change
`save_path: /plugins/plotSquared/schematics`
to
`save_path: plugins/plotSquared/schematics`
