### ISSUE TITLE
/p kick from each plot

### ISSUE THREAD

**Issue by kleinesgumi** [IntellectualCrafters/PlotSquared#229]
as normal user can i /p kick each player from her own plot in the PlotWorld.....

**Comment by boy0001** [comment]
If you are admin you can kick anyone.

**Comment by kleinesgumi** [comment]
No As Normal player with only this permissions: plots.kick player can kick each Players from players Plot. example: Player A has a own Plot. Player B has to a own Plot. now are both on own Plot. Player A write /p kick Player B and player B is kicked from her own Plot.

**Comment by boy0001** [comment]
Try: http://ci.nixium.com/job/PlotSquared/

**Comment by kleinesgumi** [comment]
Nice its fixed ;) thanks

**Comment by kleinesgumi** [comment]
new issue:
[17:00:28 ERROR]: Could not pass event EntityExplodeEvent to PlotSquared v2.8.12
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.Explosion.a(Explosion.java:181) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.World.createExplosion(World.java:1858) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.WorldServer.createExplosion(WorldServer.java:1003) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.createExplosion(CraftWorld.java:535) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.createExplosion(CraftWorld.java:531) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.createExplosion(CraftWorld.java:543) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.createExplosion(CraftWorld.java:539) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at de.blablubbabc.paintball.gadgets.handlers.ConcussionHandler$Concussion.explode(ConcussionHandler.java:148) [Paintball.jar:?]
        at de.blablubbabc.paintball.gadgets.handlers.ConcussionHandler$Concussion$1.run(ConcussionHandler.java:137) [Paintball.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
        at com.intellectualcrafters.plot.listeners.TNTListener.onExplode(TNTListener.java:32) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor632.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[craftbukkit.jar:git-Spigot-c3c767f-33d5de3]
        ... 19 more
