### ISSUE TITLE
Players lost after Server restart plots

### ISSUE THREAD

**Issue by kleinesgumi** [IntellectualCrafters/PlotSquared#264]
player get a plot and sometimes after Server restart lost the player the Plot. and the Plot not delete because the new owner is Unknown.

**Comment by boy0001** [comment]
Please update to the latest version. If the issue persists, please tell me.

**Comment by kleinesgumi** [comment]
New Error on:
[19:40:16 INFO]: KleinesGumi issued server command: /p delete
[19:40:16 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'world' in 'where clause'
[19:40:16 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:40:16 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[19:40:16 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:40:16 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[19:40:16 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[19:40:16 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:382)
[19:40:16 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
[19:40:16 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[19:40:16 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[19:40:16 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[19:40:16 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[19:40:16 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[19:40:16 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[19:40:16 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[19:40:16 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[19:40:16 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[19:40:16 WARN]:        at com.intellectualcrafters.plot.database.SQLManager$5.run(SQLManager.java:525)
[19:40:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[19:40:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:40:16 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[19:40:16 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[19:40:16 WARN]:        at java.lang.Thread.run(Thread.java:745)
[19:40:16 INFO]: [ERROR] Failed to delete plot 6;-3

Plot ist delete

**Comment by boy0001** [comment]
Thanks for the stacktrace. I have tracked down that bug and fixed it:
http://www.spigotmc.org/resources/plotsquared.1177/download?version=20545

(Still unsure if the previous bug is still an issue)

**Comment by kleinesgumi** [comment]
yes. i must wait that someone reports

**Comment by kleinesgumi** [comment]
mhh players lost still the plot ._.

**Comment by kleinesgumi** [comment]
bug is still there.
Is why server offline mode?

**Comment by boy0001** [comment]
Possibly. Are you able to check the UUID in the database?

**Comment by kleinesgumi** [comment]
yes i full access.

**Comment by boy0001** [comment]
If it's offline-mode, it will mess up if players login with usernames of different case. e.g.
`empire92` vs `Empire92`

I am working on a UUID conversion function which will allow you to convert your database to case insensitive UUIDs. See here for future updates:
https://github.com/IntellectualCrafters/PlotSquared/issues/165
