### ISSUE TITLE
problem with schematics / templates

### ISSUE THREAD

**Issue by manuk0202** [IntellectualCrafters/PlotSquared#283]
Hey there, some weeks ago someone of your Support helped me with a schematic i made. Erlyer it was possible to use AdvPlots - Schematics. Now i dont know how to use them anymore. So someone of the Support made me a template from my schematics. But this schematic is not working :/ the other templates like town.template and skyblock.template are working fine. This template i got: https://www.dropbox.com/s/28fb1em6q5ip1mp/advworld.template?dl=0
My schematics: https://mega.nz/#!BhZxiCSa!exZlJPZ2745hqDeDGhkf3fJk325StQcBb1upkWuYGXE
![bild 5](https://cloud.githubusercontent.com/assets/10981356/7250608/2c07dd7e-e824-11e4-8b3a-e0ed87b67004.png)

**Comment by boy0001** [comment]
Just tested and it works fine. I did the following to create the world:
 - Started the server
 - Download the `advworld.template` file and saved it in `plugins/PlotSquared/templates`
 - Logged onto the server
 - Used /plot template import myplotworld advworld

If this doesn't help, would you be able to send me the server log from when you tried importing the template?

Also, if you want me to come on your server and help set it up for you, I can do so this weekend.

**Comment by manuk0202** [comment]
[19:37:09] [Server thread/INFO]: [AuthMe] manu logged in!
[19:37:30] [Server thread/INFO]: manu issued server command: /plot template import myplotworld advworld
[19:37:30] [Server thread/WARN]: [Multiverse-Core] Failed to get the default chunk generator: java.lang.NoSuchMethodError: com.intellectualcrafters.plot.object.PlotGenerator.<init>(Ljava/lang/String;)V
[19:37:30] [Server thread/WARN]: [Multiverse-Core] This is a bug in AdvPlots, NOT a bug in Multiverse!
[19:37:30] [Server thread/INFO]: Invalid generator! 'AdvPlots'. [0;31;1mAborting world creation.[m
[19:37:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v2.9.17
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
	at com.intellectualcrafters.plot.util.bukkit.BukkitUtil.getSpawn(BukkitUtil.java:233) ~[?:?]
	at com.intellectualcrafters.plot.commands.Template.execute(Template.java:108) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:170) ~[?:?]
	at com.intellectualcrafters.plot.commands.BukkitCommand.onCommand(BukkitCommand.java:26) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
	... 14 more
is this enough? thx for your help

**Comment by boy0001** [comment]
You're using either an outdated version of AdvPlots or PlotSquared. Please update both plugins to the latest version.
