### ISSUE TITLE
Crashes on plugin load

### ISSUE THREAD

**Issue by Noobidoo** [IntellectualCrafters/PlotSquared#307]
Updated to the latest version from spigot site and started to get.
```
[14:32:41 ERROR]: Error occurred while enabling PlotSquared v2.10.9 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.intellectualcrafters.plot.config.C.GENERATING_WALL_FILLING
        at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.7.0_79]
        at com.intellectualcrafters.plot.config.C.valueOf(C.java:1) ~[?:?]
        at com.intellectualsites.translation.YamlTranslationFile.saveFile(YamlTranslationFile.java:149) ~[?:?]
        at com.intellectualsites.translation.YamlTranslationFile.read(YamlTranslationFile.java:237) ~[?:?]
        at com.intellectualcrafters.plot.config.C.setupTranslations(C.java:551) ~[?:?]
        at com.intellectualcrafters.plot.PlotSquared.<init>(PlotSquared.java:512) ~[?:?]
        at com.intellectualcrafters.plot.BukkitMain.onEnable(BukkitMain.java:155) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot-1.8.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.8.jar:git-Spigot-870264a-0a645a2]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
```

**Comment by Noobidoo** [comment]
Fixed it by removing the translation file. But a safety net would be good here
