### ISSUE TITLE
server runs out of memory on startup almost immediately

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#388]
http://hastebin.com/ajuyuwapuh.avrasm

did a jstack and thousand of threads like this were being made, I assume for uuid caching

**Comment by PhanaticD** [comment]
this is then shortly follow by the typical "could not create new native thread"

02:31:51] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0(Native Method) ~[?:1.8.0_45]
    at java.lang.Thread.start(Thread.java:714) ~[?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368) ~[?:1.8.0_45]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:364) ~[creative.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) ~[creative.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) ~[creative.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) ~[creative.jar:git-Spigot-f928e7a-e91aed8]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [creative.jar:git-Spigot-f928e7a-e91aed8]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by boy0001** [comment]
Could you try this version?
https://www.spigotmc.org/resources/plotsquared.1177/download?version=33497

**Comment by PhanaticD** [comment]
still happens same exact thing
