### ISSUE TITLE
Bug Report: Generating Biome with the Plugin "BiomeGenerator"

### ISSUE THREAD

**Issue by MiiAUWz** [IntellectualCrafters/PlotSquared#70]
got an error when try to generate a biome with the Plugin biomegenerator, did i made smth wrong?

[19:36:44] [Server thread/INFO]: MiiAUWz issued server command: /plot gb ocean
[19:36:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v2.5.0
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1622]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1622]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1622]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1622]
Caused by: java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/generator/DefaultPlotWorld
    at com.empcraft.biomes.GenerateBiomeCommand.execute(GenerateBiomeCommand.java:81) ~[?:?]
    at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:183) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1622]
    ... 13 more

**Comment by boy0001** [comment]
If you are still on 1.7.10:
http://www.spigotmc.org/resources/biomegenerator.1663/download?version=9354

Otherwise you will need to wait for me to update the plugin.
