### ISSUE TITLE
Purge problems

### ISSUE THREAD

**Issue by SDTCARLOS** [IntellectualCrafters/PlotSquared#74]
Hi,

We can't delete plots with purge command

im confused, this command is to delete individual plots? unclaim + clear sure?

The world is called parcelas,

when type plots purge parcelas 29;19
(Using /plot purge <world> <id> will delete a single plot and does not require the override parameter )

that show [Plot] Use /plots purge <world>;<x>;<z>, Then i type 

plots purge parcelas;29;19 and show that 

[13:28:41 INFO]: [Plot] Purge of 'parcelas;29;19' was successful!
[13:28:41 WARN]: java.sql.SQLException: Parameter index out of range (1 > number of parameters, which is 0).
[13:28:41 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[13:28:41 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[13:28:41 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[13:28:41 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[13:28:41 WARN]: at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3709)
[13:28:41 WARN]: at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3693)
[13:28:41 WARN]: at com.mysql.jdbc.PreparedStatement.setString(PreparedStatement.java:4544)
[13:28:41 WARN]: at com.intellectualcrafters.plot.database.SQLManager$11.run(SQLManager.java:870)
[13:28:41 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:71)
[13:28:41 WARN]: at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[13:28:41 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[13:28:41 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[13:28:41 WARN]: at java.lang.Thread.run(Thread.java:744)
[13:28:41 INFO]: [ERROR] FAILED TO PURGE PLOT FROM DB 'parcelas' , '29;19' !

when i go to game, the plot shows plot not claimed, but this is not reset o cleaned, and when restart the server the plot again show the owner

And i have another question, The Auto Clear, is based on last days without conecction?

Thank you!
sorry for my bad english

**Comment by boy0001** [comment]
The command should be fixed in the latest commit.

The purge command is not intended to clear the plot. It was originally created for testing purposes to unregister a plot from the server and DB. It now has a use if administrators want to remove a plotworld from the server. What are you actually trying to achieve with purge that you can't using "/plot delete"?


As for auto plot clearing, you are correct; it is based on the last time the user connected to the server.

**Comment by SDTCARLOS** [comment]
ohhh thank you

nicee the auto clear is that i need. I thought is based on chuck loaded in amount days. for this reason im try use a batch to clear lots of plots with purge based on last conection registred on crazy login.+ plotsqured db

Thank you again and nice work
