### ISSUE TITLE
conversion

### ISSUE THREAD

**Issue by ToxicWaste** [IntellectualCrafters/PlotSquared#75]
[12:35:43] [Server thread/WARN]: [PlotSquared] Task #6 for PlotSquared v2.5.2 generated an exception
java.lang.NoClassDefFoundError: com/worldcretornica/plotme/PlotManager
	at com.intellectualcrafters.plot.database.PlotMeConverter$1.run(PlotMeConverter.java:92) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-6d85d97-b389396]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-6d85d97-b389396]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-6d85d97-b389396]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-6d85d97-b389396]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-6d85d97-b389396]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-6d85d97-b389396]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: com.worldcretornica.plotme.PlotManager
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-6d85d97-b389396]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-6d85d97-b389396]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 8 more

**Comment by boy0001** [comment]
The converter has not been updated to the newer versions of PlotMe, would you happen to be using those?

**Comment by ToxicWaste** [comment]
the latest plot me yes

**Comment by boy0001** [comment]
Will be fixed in next release.
see: 1d0d85a161f7cb357c69d645c981128e1ee2a7cf

**Comment by boy0001** [comment]
Please download the next version of PlotSquared which has fixed the issue of "PlotMe forcefully disabling PlotSquared so users can't switch plugins"
