### ISSUE TITLE
Plot Cleaning // Error

### ISSUE THREAD

**Issue by Maruf61** [IntellectualCrafters/PlotSquared#84]
I understand the problem => end of page

Sorry for late response but i have still same problem i couldn't fix it yet :/ here is the stack trace

[22:19:19] [Server thread/INFO]: Maruf61[/127.0.0.1:61901] logged in with entity id 0 at ([plotw] -167.83704108589518, 65.0, 1197.9464561325758)
[22:19:23] [Server thread/INFO]: Maruf61 issued server command: /p clear
[22:19:23] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'p' in plugin PlotSquared v2.5.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1571]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1571]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1010) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:847) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1571]
Caused by: java.lang.AbstractMethodError: com.intellectualcrafters.plot.object.PlotManager.clearPlot(Lorg/bukkit/World;Lcom/intellectualcrafters/plot/object/Plot;Z)Z
	at com.intellectualcrafters.plot.util.PlotHelper.clear(PlotHelper.java:694) ~[?:?]
	at com.intellectualcrafters.plot.util.PlotHelper.clear(PlotHelper.java:734) ~[?:?]
	at com.intellectualcrafters.plot.object.Plot.clear(Plot.java:348) ~[?:?]
	at com.intellectualcrafters.plot.commands.Clear.execute(Clear.java:79) ~[?:?]
	at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:183) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1571]
	... 13 more

+ when i try to use /p debugclear it says you are not in a plot.

+ the problem is about AdvPlots. Can you Please Update AdvPlots Plugin.

**Comment by boy0001** [comment]
I may have already said this, but I suggest you switch to the default generator, which has schematic support now.

I'll update AdvPlots at some point, but it's becoming obsolete, as it's harder to use, generally buggier, and most functionality is being added to the default generator.

**Comment by boy0001** [comment]
Should be fixed now.
